=== Tencent/TencentKona-8/hotspot/src/share/vm/trace/trace.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2012, 2013, Oracle and/or its affiliates. All rights reserved.
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.

 This code is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License version 2 only, as
 published by the Free Software Foundation.

 This code is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 version 2 for more details (a copy is included in the LICENSE file that
 accompanied this code).

 You should have received a copy of the GNU General Public License version
 2 along with this work; if not, write to the Free Software Foundation,
 Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

 Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 or visit www.oracle.com if you need additional information or have any
 questions.
  
-->

<!ELEMENT trace (xi:include, relation_decls, events*, xi:include, xi:include)>
<!ELEMENT types (content_types, primary_types)>
<!ELEMENT content_types (content_type|struct_type)*>
<!ELEMENT content_type (value|structvalue|structarray|array)*>
<!ELEMENT struct_type (value*)>
<!ELEMENT primary_types (primary_type*)>
<!ELEMENT primary_type EMPTY>
<!ELEMENT relation_decls (relation_decl*)>
<!ELEMENT relation_decl EMPTY>
<!ELEMENT events (event|struct)*>
<!ELEMENT event (value|structvalue)*>
<!ELEMENT struct (value|structvalue)*>
<!ELEMENT value EMPTY>
<!ELEMENT structvalue EMPTY>
<!ELEMENT structarray EMPTY>
<!ELEMENT array EMPTY>
<!ATTLIST content_type  id             CDATA #REQUIRED
                        hr_name        CDATA #REQUIRED
                        type           CDATA #REQUIRED
                        jvm_type       CDATA #IMPLIED
                        builtin_type   CDATA #IMPLIED>
<!ATTLIST struct_type   id             CDATA #REQUIRED>
<!ATTLIST structarray   type           CDATA #REQUIRED
                        field          CDATA #REQUIRED
                        label          CDATA #REQUIRED>
<!ATTLIST primary_type  symbol         CDATA #REQUIRED
                        datatype       CDATA #REQUIRED
                        contenttype    CDATA #REQUIRED
                        type           CDATA #REQUIRED
                        sizeop         CDATA #REQUIRED>
<!ATTLIST relation_decl id             CDATA #REQUIRED
                        uri            CDATA #REQUIRED>
<!ATTLIST event         id             CDATA #REQUIRED
                        path           CDATA #REQUIRED
                        label          CDATA #REQUIRED
                        description    CDATA #IMPLIED
                        has_thread     CDATA "false"
                        ignore_check   CDATA "false"
                        has_stacktrace CDATA "false"
                        is_instant     CDATA "false"
                        is_constant    CDATA "false"
                        is_requestable CDATA "false">
<!ATTLIST struct        id             CDATA #REQUIRED>
<!ATTLIST value         type           CDATA #REQUIRED
                        field          CDATA #REQUIRED
                        label          CDATA #REQUIRED
                        description    CDATA #IMPLIED
                        relation       CDATA "NOT_AVAILABLE"
                        transition     CDATA "NONE">
<!ATTLIST array         type           CDATA #REQUIRED
                        field          CDATA #REQUIRED
                        label          CDATA #REQUIRED
                        description    CDATA #IMPLIED>
<!ATTLIST structarray   type           CDATA #REQUIRED
                        field          CDATA #REQUIRED
                        label          CDATA #REQUIRED
                        description    CDATA #IMPLIED>
<!ATTLIST structvalue   type           CDATA #REQUIRED
                        field          CDATA #REQUIRED
                        label          CDATA #REQUIRED
                        description    CDATA #IMPLIED>

=== Tencent/TencentKona-8/hotspot/src/share/vm/trace/trace.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 Copyright (c) 2012, 2015, Oracle and/or its affiliates. All rights reserved.
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.

 This code is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License version 2 only, as
 published by the Free Software Foundation.

 This code is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 version 2 for more details (a copy is included in the LICENSE file that
 accompanied this code).

 You should have received a copy of the GNU General Public License version
 2 along with this work; if not, write to the Free Software Foundation,
 Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

 Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 or visit www.oracle.com if you need additional information or have any
 questions.

-->


<!DOCTYPE trace SYSTEM "trace.dtd" [
<!ENTITY % xinclude SYSTEM "xinclude.mod">
%xinclude;
]>

<trace>
  <xi:include href="tracetypes.xml" xmlns:xi="http://www.w3.org/2001/XInclude"/>

  <relation_decls>
    <relation_decl id="GC_ID" uri="vm/gc/id"/>
    <relation_decl id="COMP_ID" uri="vm/compiler/id"/>
    <relation_decl id="SWEEP_ID" uri="vm/code_sweeper/id"/>
    <relation_decl id="JAVA_MONITOR_ADDRESS" uri="java/monitor/address"/>
  </relation_decls>

<!--

Events in the JVM are by default timed (it's more common)
Perhaps a little strange. Might change.

EVENTS

Declard with the 'event' tag.

<value fields> can be one or more of
   value            - a simple primitive or constant type value
   structvalue      - value is a sub-struct. This type must be previously defined
                      with 'struct'
All these require you to declare type, field and label of the field. They also accept
an optional description of the field. If the meaning of the field is not obvious
from the label you should provide a description. If an event however is not actually
meant for end-users, you should probably _not_ write descriptions at all, since you
might just add more concepts the user has no notion of/interest in.

Events should be modeled after what conceptual process you are expressing, _NOT_
from whatever data structures you might use inside the JVM for expressing a process.


STRUCT

Declared with the 'struct' tag.

Declares a structure type that can be used in other events.

-->

  <events>
    <event id="ThreadStart" path="java/thread_start" label="Java Thread Start"
           has_thread="true" is_instant="true">
      <value type="JAVALANGTHREAD" field="javalangthread" label="Java Thread"/>
    </event>

    <event id="ThreadEnd" path="java/thread_end" label="Java Thread End"
           has_thread="true" is_instant="true">
      <value type="JAVALANGTHREAD" field="javalangthread" label="Java Thread"/>
    </event>

    <event id="ThreadSleep" path="java/thread_sleep" label="Java Thread Sleep"
            has_thread="true" has_stacktrace="true" is_instant="false">
      <value type="MILLIS" field="time" label="Sleep Time"/>
    </event>

    <event id="ThreadPark" path="java/thread_park" label="Java Thread Park"
            has_thread="true" has_stacktrace="true" is_instant="false">
      <value type="CLASS" field="klass" label="Class Parked On"/>
      <value type="MILLIS" field="timeout" label="Park Timeout"/>
      <value type="ADDRESS" field="address" label="Address of Object Parked" relation="JAVA_MONITOR_ADDRESS"/>
    </event>

    <event id="JavaMonitorEnter" path="java/monitor_enter" label="Java Monitor Blocked"
            has_thread="true" has_stacktrace="true" is_instant="false">
      <value type="CLASS" field="klass" label="Monitor Class"/>
      <value type="JAVALANGTHREAD" field="previousOwner" label="Previous Monitor Owner"/>
      <value type="ADDRESS" field="address" label="Monitor Address" relation="JAVA_MONITOR_ADDRESS"/>
    </event>

    <event id="JavaMonitorWait" path="java/monitor_wait" label="Java Monitor Wait" description="Waiting on a Java monitor"
            has_thread="true" has_stacktrace="true" is_instant="false">
      <value type="CLASS" field="klass" label="Monitor Class" description="Class of object waited on"/>
      <value type="OSTHREAD" field="notifier" label="Notifier Thread" description="Notifying Thread"/>
      <value type="MILLIS" field="timeout" label="Timeout" description="Maximum wait time"/>
      <value type="BOOLEAN" field="timedOut" label="Timed Out" description="Wait has been timed out"/>
      <value type="ADDRESS" field="address" label="Monitor Address" description="Address of object waited on" relation="JAVA_MONITOR_ADDRESS"/>
    </event>

    <event id="ClassLoad" path="vm/class/load" label="Class Load"
            has_thread="true" has_stacktrace="true" is_instant="false">
      <value type="CLASS" field="loadedClass" label="Loaded Class"/>
      <value type="CLASS" field="definingClassLoader" label="Defining Class Loader"/>
      <value type="CLASS" field="initiatingClassLoader" label="Initiating Class Loader"/>
    </event>

    <event id="ClassUnload" path="vm/class/unload" label="Class Unload"
        has_thread="true" is_instant="true">
      <value type="CLASS" field="unloadedClass" label="Unloaded Class"/>
      <value type="CLASS" field="definingClassLoader" label="Defining Class Loader"/>
    </event>

    <event id="LongFlagChanged" path="vm/flag/long_changed" label="Long Flag Changed"
          is_instant="true">
      <value type="UTF8" field="name" label="Name" />
      <value type="LONG" field="old_value" label="Old Value" />
      <value type="LONG" field="new_value" label="New Value" />
      <value type="FLAGVALUEORIGIN" field="origin" label="Origin" />
    </event>

    <event id="UnsignedLongFlagChanged" path="vm/flag/ulong_changed" label="Unsigned Long Flag Changed"
          is_instant="true">
      <value type="UTF8" field="name" label="Name" />
      <value type="ULONG" field="old_value" label="Old Value" />
      <value type="ULONG" field="new_value" label="New Value" />
      <value type="FLAGVALUEORIGIN" field="origin" label="Origin" />
    </event>

    <event id="DoubleFlagChanged" path="vm/flag/double_changed" label="Double Flag Changed"
         is_instant="true">
      <value type="UTF8" field="name" label="Name" />
      <value type="DOUBLE" field="old_value" label="Old Value" />
      <value type="DOUBLE" field="new_value" label="New Value" />
      <value type="FLAGVALUEORIGIN" field="origin" label="Origin" />
    </event>

    <event id="BooleanFlagChanged" path="vm/flag/boolean_changed" label="Boolean Flag Changed"
         is_instant="true">
      <value type="UTF8" field="name" label="Name" />
      <value type="BOOLEAN" field="old_value" label="Old Value" />
      <value type="BOOLEAN" field="new_value" label="New Value" />
      <value type="FLAGVALUEORIGIN" field="origin" label="Origin" />
    </event>

    <event id="StringFlagChanged" path="vm/flag/string_changed" label="String Flag Changed"
         is_instant="true">
      <value type="UTF8" field="name" label="Name" />
      <value type="UTF8" field="old_value" label="Old Value" />
      <value type="UTF8" field="new_value" label="New Value" />
      <value type="FLAGVALUEORIGIN" field="origin" label="Origin" />
    </event>

    <struct id="VirtualSpace">
      <value type="ADDRESS" field="start" label="Start Address" description="Start address of the virtual space" />
      <value type="ADDRESS" field="committedEnd" label="Committed End Address" description="End address of the committed memory for the virtual space" />
      <value type="BYTES64" field="committedSize" label="Committed Size" description="Size of the committed memory for the virtual space" />
      <value type="ADDRESS" field="reservedEnd" label="Reserved End Address" description="End address of the reserved memory for the virtual space" />
      <value type="BYTES64" field="reservedSize" label="Reserved Size" description="Size of the reserved memory for the virtual space" />
    </struct>

    <struct id="ObjectSpace">
      <value type="ADDRESS" field="start" label="Start Address" description="Start address of the space" />
      <value type="ADDRESS" field="end" label="End Address" description="End address of the space" />
      <value type="BYTES64" field="used" label="Used" description="Bytes allocated by objects in the space" />
      <value type="BYTES64" field="size" label="Size" description="Size of the space" />
    </struct>

    <event id="GCHeapSummary" path="vm/gc/heap/summary" label="Heap Summary" is_instant="true">
      <value type="UINT" field="gcId" label="GC ID" relation="GC_ID"/>
      <value type="GCWHEN" field="when" label="When" />
      <structvalue type="VirtualSpace" field="heapSpace" label="Heap Space"/>
      <value type="BYTES64" field="heapUsed" label="Heap Used" description="Bytes allocated by objects in the heap"/>
    </event>

    <struct id="MetaspaceSizes">
      <value type="BYTES64" field="committed" label="Committed" description="Committed memory for this space" />
      <value type="BYTES64" field="used" label="Used" description="Bytes allocated by objects in the space" />
      <value type="BYTES64" field="reserved" label="Reserved" description="Reserved memory for this space" />
    </struct>

    <event id="MetaspaceSummary" path="vm/gc/heap/metaspace_summary" label="Metaspace Summary" is_instant="true">
      <value type="UINT" field="gcId" label="GC ID" relation="GC_ID"/>
      <value type="GCWHEN" field="when" label="When" />
      <value type="BYTES64" field="gcThreshold" label="GC Threshold" />
      <structvalue type="MetaspaceSizes" field="metaspace" label="Total"/>
      <structvalue type="MetaspaceSizes" field="dataSpace" label="Data"/>
